import{i as c,S as m}from"./assets/vendor-8c59ed88.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();function f(s){const r="https://pixabay.com/api/",o=new URLSearchParams({key:"43216029-fdbabf479345253dcfedb0f85",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}),n=`${r}?${o}`;return fetch(n).then(e=>e.json()).catch(e=>{throw console.error("Error occurred while fetching images:",e),e})}const l=document.querySelector(".gallery");function u(s){if(s.length===0)c.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"}),i();else{const r=s.map(o=>`<li class="item-image"><a class="photos-list-link" href="${o.largeImageURL}">
  <img class="photo" src="${o.webformatURL}" alt="${o.tags}"/>
  </a>
  <ul class="photo-information-container">
  <li class="item-photo-information-container"><p><span class="accent">Likes</span>${o.likes}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Views</span>${o.views}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Comments</span>${o.comments}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Downloads</span>${o.downloads}</p></li>
  </ul>
  </li>`).join("");l.insertAdjacentHTML("beforeend",r),h.refresh()}i()}const h=new m(".gallery a",{captionsData:"alt",captionDelay:250}),p=document.querySelector(".loader"),d=document.querySelector(".search-form");function g(){p.classList.remove("is-hidden")}function i(){p.classList.add("is-hidden")}d.addEventListener("submit",y);function y(s){s.preventDefault(),g(),l.innerHTML="";const r=s.target.elements.search.value.trim();r!==""?f(r).then(o=>{u(o.hits),d.reset()}).catch(o=>{console.log(o),c.error({message:"Sorry, an error occurred while loading. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"}),i()}):(c.show({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"}),i())}
//# sourceMappingURL=commonHelpers.js.map
